// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBK7Gdl5O1juAu7paONjSXaf1P-1hri6Ew',
    appId: '1:1070545470779:android:93634792a1478079c7e31e',
    messagingSenderId: '1070545470779',
    projectId: 'ihcs-1ff9c',
    storageBucket: 'ihcs-1ff9c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAavVQq5b4RL4_bmDUedbvxg0GomT72Yes',
    appId: '1:1070545470779:ios:1f568512eef023c7c7e31e',
    messagingSenderId: '1070545470779',
    projectId: 'ihcs-1ff9c',
    storageBucket: 'ihcs-1ff9c.firebasestorage.app',
    iosBundleId: 'com.example.hamaltekk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9dbX1rgj-WuqINXFIbxUnRBVqJni1GF0',
    appId: '1:1070545470779:web:a5dd9682655b6634c7e31e',
    messagingSenderId: '1070545470779',
    projectId: 'ihcs-1ff9c',
    authDomain: 'ihcs-1ff9c.firebaseapp.com',
    storageBucket: 'ihcs-1ff9c.firebasestorage.app',
    measurementId: 'G-5TSWCZY33E',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9dbX1rgj-WuqINXFIbxUnRBVqJni1GF0',
    appId: '1:1070545470779:web:a5dd9682655b6634c7e31e',
    messagingSenderId: '1070545470779',
    projectId: 'ihcs-1ff9c',
    authDomain: 'ihcs-1ff9c.firebaseapp.com',
    storageBucket: 'ihcs-1ff9c.firebasestorage.app',
    measurementId: 'G-5TSWCZY33E',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAavVQq5b4RL4_bmDUedbvxg0GomT72Yes',
    appId: '1:1070545470779:ios:1f568512eef023c7c7e31e',
    messagingSenderId: '1070545470779',
    projectId: 'ihcs-1ff9c',
    storageBucket: 'ihcs-1ff9c.firebasestorage.app',
    iosBundleId: 'com.example.hamaltekk',
  );

}